import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1>Titre principal</h1>
        <Link href="/actions/un-id">
          <a>Actions de Kendji</a>
        </Link>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}

export default Home
