import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
            rel="preload"
            href='/fonts/Rubik/static/Rubik-Regular.ttf'
            as="font"
            crossOrigin=""
          />
      </Head>

      <main >
        <h1 className='h1'>Titre principal</h1>
        <Link href="/jeunes/kendji/actions">
          <a>Actions de Kendji</a>
        </Link>
      </main>

      <footer >
        
      </footer>
    </div>
  )
}

export default Home
