import { UserAction } from "interfaces"

const now = new Date()

const actionsPredefinies : UserAction[] = [
  {
    id: 'no-com-1',
    content: 'Identifier ses atouts et ses compétences',
    comment: 'Hello from comment',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: 'no-com-2',
    content: 'Identifier des pistes de métier',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: 'no-com-3',
    content: 'Identifier des entreprises',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: 'no-com-4',
    content: "Contacter un employeur pour effectuer une période d'immersion en entreprise",
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '1',
    content: 'Effectuer une enquête métier',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '2',
    content: 'Participer à un salon/ un forum',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '3',
    content: "S'informer sur une formation",
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '4',
    content: 'Contacter un organisme de formation',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '5',
    content: 'Ouvrir son compte personnel de formation',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '6',
    content: 'Mettre à jour son CV',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '7',
    content: 'Rédiger une lettre de motivation',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '8',
    content: "Consulter les offres d'emploi",
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '9',
    content: "Répondre à une offre d'emploi",
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '10',
    content: 'Effectuer des candidatures spontanées',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '11',
    content: 'Tenir un tableau de prospection',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '12',
    content: "Se rendre à un entretien d'embauche",
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '13',
    content: 'Rechercher des informations pour créer ou reprendre une entreprise',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '14',
    content: 'Contacter la mission locale',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '15',
    content: 'Contacter un organisme de prestations sociales (ex CAF, CPAM, MSA)',
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
  {
    id: '16',
    content: "S'informer pour une mobilité à l'étranger",
    comment: '',
    isDone: false,
    creationDate: now,
    lastUpdate: now,
  },
]

export {actionsPredefinies}