/**
 * Shared Layout, see: https://nextjs.org/docs/basic-features/layouts
 */

 import Head from 'next/head'

 import Header from './Header'
 import Sidebar from './Sidebar'
 import ChatBox from './ChatRoom'


 import styles from 'styles/components/Layouts.module.css'

type LayoutProps = {
  children: any
}

export default function Layout({ children }: LayoutProps) {
   return (
     <>
     <Head>
       <title>Create Next App</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
       <link
           rel="preload"
           href='/fonts/Rubik/static/Rubik-Regular.ttf'
           as="font"
           crossOrigin=""
         />
     </Head>
      <Header />
      <div style={{position: "relative"}}>
          <Sidebar />
          <main className={styles.page} role="main">{children}</main>
          <div id="modal-root"></div>
          <ChatBox /> 
      </div>
     </>
   )
 }